import { CluesInputOriginal } from '@jaredreisinger/react-crossword/dist/types';
import { CrosswordType } from './types';

export const data1: CluesInputOriginal = {
	across: {
		1: {
			clue: 'one plus one',
			answer: 'TWO',
			row: 0,
			col: 0,
		},
		3: {
			clue: 'two plus two',
			answer: 'error',
			row: 2,
			col: 2,
		},
	},
	down: {
		2: {
			clue: 'three minus two',
			answer: 'ONE',
			row: 0,
			col: 2,
		},
		4: {
			clue: 'three minus two',
			answer: 'ONE',
			row: 2,
			col: 5,
		},
		5: {
			clue: 'Guess a few more to get this hint',
			answer: 'ONE',
			row: 4,
			col: 3,
		},
	},
};

// export const data2: CrosswordType = {
// 	currentTimer: 600,
// 	initialTimer: 600,
// 	completed: false,
// 	crossword: {
// 		across: {
// 			3: {
// 				clue: 'Hvad laver du egentlig?',
// 				answer: 'DEVOPS',
// 				row: 5,
// 				col: 7,
// 				completed: false,
// 			},
// 			7: {
// 				clue: 'Hvad kan og vil en svane brække?',
// 				answer: 'ARM',
// 				row: 7,
// 				col: 12,
// 				completed: false,
// 			},
// 			8: {
// 				clue: 'Dødbringende ikke-rigtig-nød',
// 				answer: 'PEANUT',
// 				row: 8,
// 				col: 0,
// 				completed: false,
// 			},
// 			9: {
// 				clue: 'Hvorfor er C# bedre end python?',
// 				answer: 'HURTIGERE',
// 				row: 9,
// 				col: 5,
// 				completed: false,
// 			},
// 			11: {
// 				clue: 'De bedste settings',
// 				answer: 'SRØNZ',
// 				row: 11,
// 				col: 2,
// 				completed: false,
// 			},
// 			12: {
// 				clue: 'Svaret kan findes der, hvor passwords bedst opbevares',
// 				answer: 'ISWAN',
// 				row: 13,
// 				col: 9,
// 				completed: false,
// 			},
// 			14: {
// 				clue: 'Navnet på byen der ligger 33 grader, 16 bueminutter og 11 buesekunder nordlig bredde og 96 grader, 19 bueminutter og 52 buesekunder vestlig længde?',
// 				answer: 'ARNOLD',
// 				row: 0,
// 				col: 7,
// 				completed: false,
// 			},
// 			15: {
// 				clue: 'Slap A-PI',
// 				answer: 'REST',
// 				row: 7,
// 				col: 0,
// 				completed: false,
// 			},
// 		},
// 		down: {
// 			1: {
// 				clue: 'Tema for deep fried Olsen Banden meme onsdag d. 7. december',
// 				answer: 'DEMENS',
// 				row: 0,
// 				col: 12,
// 				completed: false,
// 			},
// 			2: {
// 				clue: 'Bevinget og berigende dyr',
// 				answer: 'SVANE',
// 				row: 5,
// 				col: 3,
// 				completed: false,
// 			},
// 			4: {
// 				clue: 'Kunder elsker, når deres søgning er...',
// 				answer: 'ELASTISK',
// 				row: 5,
// 				col: 8,
// 				completed: false,
// 			},
// 			5: {
// 				clue: 'Slangehviskerens sprog',
// 				answer: 'PYTHON',
// 				row: 6,
// 				col: 5,
// 				completed: false,
// 			},
// 			6: {
// 				clue: 'Hvis man siger Franz er dårlig til CS, så har man...',
// 				answer: 'RET',
// 				row: 7,
// 				col: 1,
// 				completed: false,
// 			},
// 			7: {
// 				clue: 'Ubrugelig Pokémon uden ske',
// 				answer: 'ABRA',
// 				row: 7,
// 				col: 12,
// 				completed: false,
// 			},
// 			10: {
// 				clue: 'What do slay today?',
// 				answer: 'GOATS',
// 				row: 9,
// 				col: 10,
// 				completed: false,
// 			},
// 			13: {
// 				clue: 'Fornavnet på den der spillede hovedrollen i den bedste julefilm nogensinde der starter med "Jingle"?',
// 				answer: 'ARNOLD',
// 				row: 0,
// 				col: 7,
// 				completed: false,
// 			},
// 		},
// 	},
// };

// same data but every column is 2 higher
export const data3: CrosswordType = {
	currentTimer: 600,
	initialTimer: 600,
	completed: false,
	crossword: {
		across: {
			3: {
				clue: 'Hvad laver du egentlig?',
				answer: 'DEVOPS',
				row: 5,
				col: 9,
				completed: false,
			},
			7: {
				clue: 'Hvad kan og vil en svane brække? (se 21)',
				answer: 'ARM',
				row: 7,
				col: 14,
				completed: false,
			},
			8: {
				clue: 'Dødbringende ikke-rigtig-nød',
				answer: 'PEANUT',
				row: 8,
				col: 2,
				completed: false,
			},
			9: {
				clue: 'Hvorfor er C# bedre end python?',
				answer: 'HURTIGERE',
				row: 9,
				col: 7,
				completed: false,
			},
			11: {
				clue: 'De bedste settings (se 17)',
				answer: 'SRØNZ',
				row: 11,
				col: 4,
				completed: false,
			},
			12: {
				clue: 'Svaret kan findes der, hvor passwords bedst opbevares i browseren',
				answer: 'ISWAN',
				row: 13,
				col: 11,
				completed: false,
			},
			14: {
				clue: 'Navnet på byen der ligger 33 grader, 16 bueminutter og 11 buesekunder nordlig bredde og 96 grader, 19 bueminutter og 52 buesekunder vestlig længde?',
				answer: 'ARNOLD',
				row: 0,
				col: 9,
				completed: false,
			},
			18: {
				clue: 'Slap A-PI',
				answer: 'REST',
				row: 9,
				col: 0,
				completed: false,
			},
			19: {
				clue: 'Billigste shotgun is CS',
				answer: 'NOVA',
				row: 3,
				col: 8,
				completed: false,
			},
		},
		down: {
			1: {
				clue: 'Dette rammer åbenbart anderledes ifølge et deep fried Olsen Banden meme fra onsdag d. 7. december',
				answer: 'DEMENS',
				row: 0,
				col: 14,
				completed: false,
			},
			2: {
				clue: 'Et bevinget og berigende dyr',
				answer: 'SVANE',
				row: 5,
				col: 5,
				completed: false,
			},
			4: {
				clue: 'Kunder elsker, når deres søgning er...',
				answer: 'ELASTISK',
				row: 5,
				col: 10,
				completed: false,
			},
			5: {
				clue: 'Slangehviskeri',
				answer: 'PYTHON',
				row: 6,
				col: 7,
				completed: false,
			},
			6: {
				clue: 'Hvis man siger Franz er dårlig til CS, så har man...',
				answer: 'RET',
				row: 7,
				col: 3,
				completed: false,
			},
			10: {
				clue: 'What to slay today?',
				answer: 'GOATS',
				row: 9,
				col: 12,
				completed: false,
			},
			13: {
				clue: 'Fornavnet på den der spillede hovedrollen i den bedste julefilm nogensinde der starter med "Jingle"?',
				answer: 'ARNOLD',
				row: 0,
				col: 9,
				completed: false,
			},
			15: {
				clue: 'Ikke XBOX eller PC',
				answer: 'PS',
				row: 8,
				col: 2,
				completed: false,
			},
			16: {
				clue: 'Skal oftest ikke vare ved for evigt',
				answer: 'LOOP',
				row: 4,
				col: 12,
				completed: false,
			},
			17: {
				clue: 'Kan enten være noget der daler eller noget der stiger op... i næsen',
				answer: 'SNE',
				row: 11,
				col: 4,
				completed: false,
			},
			20: {
				clue: 'Antallet af udviklere i IT Minds der har erfaring med at udvikle til Windows Phone',
				answer: 'EN',
				row: 12,
				col: 15,
				completed: false,
			},
			21: {
				clue: 'Ubrugelig Pokémon uden ske',
				answer: 'ABRA',
				row: 7,
				col: 14,
				completed: false,
			},
		},
	},
};
