import { CluesInputOriginal } from '@jaredreisinger/react-crossword/dist/types';
import { CrosswordType } from './types';

export const data1: CluesInputOriginal = {
	across: {
		1: {
			clue: 'one plus one',
			answer: 'TWO',
			row: 0,
			col: 0,
		},
		3: {
			clue: 'two plus two',
			answer: 'error',
			row: 2,
			col: 2,
		},
	},
	down: {
		2: {
			clue: 'three minus two',
			answer: 'ONE',
			row: 0,
			col: 2,
		},
		4: {
			clue: 'three minus two',
			answer: 'ONE',
			row: 2,
			col: 5,
		},
		5: {
			clue: 'Guess a few more to get this hint',
			answer: 'ONE',
			row: 4,
			col: 3,
		},
	},
};

export const data3: CrosswordType = {
	currentTimer: 1200,
	initialTimer: 1200,
	shouldSorenBeTryingToCheat: 'no! stop!',
	completed: false,
	something: [],
	crossword: {
		across: {
			3: {
				clue: 'Hvad laver du egentlig?',
				answer: 'DEVOPS',
				row: 5,
				col: 9,
				completed: false,
				id: '3',
			},
			7: {
				clue: 'Hvilket dyr har lyden der kommer, hvis du taster "GRYNT" og giver bælgfrugter, når den ikke kan mere?',
				answer: 'HVALROS',
				row: 1,
				col: 5,
				completed: false,

				id: '7',
			},
			8: {
				clue: 'Dødbringende ikke-rigtig-nød',
				answer: 'PEANUT',
				row: 8,
				col: 2,
				completed: false,
				id: '8',
			},
			9: {
				clue: 'Bare én af grundene til at er C# bedre end python',
				answer: 'HURTIGERE',
				row: 9,
				col: 7,
				completed: false,
				id: '9',
			},
			11: {
				clue: 'De bedste settings (se 17)',
				answer: 'SRØNZ',
				row: 11,
				col: 4,
				completed: false,
				id: '11',
			},
			12: {
				clue: 'Hvilket navn var der på den første seddel?',
				answer: 'ISWAN',
				row: 13,
				col: 11,
				completed: false,
				id: '12',
			},
			14: {
				clue: 'Navnet på byen der ligger 33 grader, 16 bueminutter og 11 buesekunder nordlig bredde og 96 grader, 19 bueminutter og 52 buesekunder vestlig længde?',
				answer: 'ARNOLD',
				row: 0,
				col: 9,
				completed: false,
				id: '14',
			},
			18: {
				clue: 'Slap A-PI',
				answer: 'REST',
				row: 9,
				col: 0,
				completed: false,
				id: '18',
			},
			19: {
				clue: 'Billigste shotgun is CS',
				answer: 'NOVA',
				row: 3,
				col: 8,
				completed: false,
				id: '19',
			},
			24: {
				clue: 'Hvad kan og vil en svane brække? (se 21)',
				answer: 'ARM',
				row: 7,
				col: 14,
				completed: false,
				id: '24',
			},
		},
		down: {
			1: {
				clue: 'Dette rammer åbenbart anderledes ifølge et deep fried Olsen Banden meme fra onsdag d. 7. december i meme-shitty',
				answer: 'DEMENS',
				row: 0,
				col: 14,
				completed: false,
				id: '1',
			},
			2: {
				clue: 'Et bevinget og berigende dyr',
				answer: 'SVANE',
				row: 5,
				col: 5,
				completed: false,
				id: '2',
			},
			4: {
				clue: 'Kunder elsker, når deres søgning er...',
				answer: 'ELASTISK',
				row: 5,
				col: 10,
				completed: false,
				id: '4',
			},
			5: {
				clue: 'Slangehviskeri',
				answer: 'PYTHON',
				row: 6,
				col: 7,
				completed: false,
				id: '5',
			},
			6: {
				clue: 'Hvis man siger Franz er dårlig til CS, så har man...',
				answer: 'RET',
				row: 7,
				col: 3,
				completed: false,
				id: '6',
			},
			10: {
				clue: 'What to slay today?',
				answer: 'GOATS',
				row: 9,
				col: 12,
				completed: false,
				id: '10',
			},
			13: {
				clue: 'Fornavnet på den der spillede hovedrollen i den bedste julefilm nogensinde der starter med "Jingle"',
				answer: 'ARNOLD',
				row: 0,
				col: 9,
				completed: false,
				id: '13',
			},
			15: {
				clue: 'Ikke XBOX eller PC',
				answer: 'PS',
				row: 8,
				col: 2,
				completed: false,
				id: '15',
			},
			16: {
				clue: 'Skal oftest ikke vare ved for evigt i programmering',
				answer: 'LOOP',
				row: 4,
				col: 12,
				completed: false,
				id: '16',
			},
			17: {
				clue: 'Kan enten være noget der daler eller noget der stiger op... i næsen',
				answer: 'SNE',
				row: 11,
				col: 4,
				completed: false,
				id: '17',
			},
			20: {
				clue: 'Antallet af udviklere i IT Minds der har erfaring med at udvikle til Windows Phone',
				answer: 'EN',
				row: 12,
				col: 15,
				completed: false,
				id: '20',
			},
			21: {
				clue: 'Ubrugelig Pokémon uden ske',
				answer: 'ABRA',
				row: 7,
				col: 14,
				completed: false,
				id: '21',
			},
			22: {
				clue: 'Hvad er der en smule mindre af på kontoret, når der spilles autopets?',
				answer: 'RO',
				row: 0,
				col: 10,
				completed: false,
				id: '22',
			},
			23: {
				clue: 'Et nanosekund',
				answer: 'NS',
				row: 0,
				col: 11,
				completed: false,
				id: '23',
			},
		},
	},
};
